// Polish first name diminutives mapping
const diminutives: Record<string, string> = {
  // Male names
  'przemysław': 'Przemek',
  'przemyslaw': 'Przemek',
  'krzysztof': 'Krzysiek',
  'jan': 'Janek',
  'piotr': 'Piotrek',
  'paweł': 'Pawełek',
  'pawel': 'Pawelek',
  'andrzej': 'Andrzejek',
  'tomasz': 'Tomek',
  'marcin': 'Marcinek',
  'michał': 'Michałek',
  'michal': 'Michalek',
  'jakub': 'Kuba',
  'łukasz': 'Łukasz',
  'lukasz': 'Łukasz',
  'mateusz': 'Mateuszek',
  'adam': 'Adaś',
  'robert': 'Robert',
  'sebastian': 'Sebek',
  'wojciech': 'Wojtek',
  'maciej': 'Maciek',
  'grzegorz': 'Grzesiek',
  'rafał': 'Rafałek',
  'rafal': 'Rafalek',
  'daniel': 'Daniel',
  'kamil': 'Kamil',
  'aleksander': 'Olek',
  'bartosz': 'Bartek',
  'dawid': 'Dawid',
  'dominik': 'Dominik',
  'karol': 'Karolek',
  'szymon': 'Szymon',
  'damian': 'Damianek',
  'patryk': 'Patryk',
  'artur': 'Arturek',
  'konrad': 'Konrad',
  'filip': 'Filipek',
  'adrian': 'Adrian',
  'mariusz': 'Mariuszek',
  'dariusz': 'Darek',
  'stanisław': 'Staszek',
  'stanislaw': 'Staszek',
  'zbigniew': 'Zbyszek',
  'jerzy': 'Jurek',
  'tadeusz': 'Tadek',
  'ryszard': 'Rysiek',
  'henryk': 'Heniek',
  'kazimierz': 'Kazik',
  'marek': 'Marek',
  'janusz': 'Janusz',
  'józef': 'Józek',
  'jozef': 'Józek',
  'edward': 'Edek',
  'władysław': 'Władek',
  'wladyslaw': 'Władek',
  'bogdan': 'Bogdan',
  'zenon': 'Zenek',
  'wiesław': 'Wiesiek',
  'wieslaw': 'Wiesiek',
  'czesław': 'Czesiek',
  'czeslaw': 'Czesiek',
  'leszek': 'Leszek',
  'mirosław': 'Mirek',
  'miroslaw': 'Mirek',
  'jarosław': 'Jarek',
  'jaroslaw': 'Jarek',
  'bogusław': 'Bogusiek',
  'boguslaw': 'Bogusiek',
  'eugeniusz': 'Geniusz',
  'stefan': 'Stefek',
  'roman': 'Romek',
  'leon': 'Leonek',
  'franciszek': 'Franek',
  'antoni': 'Antek',
  'bronisław': 'Bronek',
  'bronislaw': 'Bronek',
  'zygmunt': 'Zygmuś',
  'witold': 'Witek',
  'leonard': 'Leoś',
  'ernest': 'Ernestek',
  'oskar': 'Oskarek',
  'igor': 'Igor',
  'bruno': 'Bruno',
  'hubert': 'Hubert',
  'kacper': 'Kacperek',
  'nikodem': 'Nikodemek',
  'marcel': 'Marcelek',
  'alan': 'Alanek',
  'oliwier': 'Oliwierek',
  'tymon': 'Tymonek',
  'maksymilian': 'Maks',
  'wiktor': 'Wiktorek',
  'aleksy': 'Olek',
  'julian': 'Julianek',
  'mikołaj': 'Mikołajek',
  'mikolaj': 'Mikołajek',
  
  // Female names
  'anna': 'Ania',
  'maria': 'Marysia',
  'katarzyna': 'Kasia',
  'małgorzata': 'Małgosia',
  'malgorzata': 'Małgosia',
  'agnieszka': 'Agnieszka',
  'barbara': 'Basia',
  'ewa': 'Ewka',
  'krystyna': 'Krysia',
  'elżbieta': 'Ela',
  'elzbieta': 'Ela',
  'zofia': 'Zosia',
  'teresa': 'Terenia',
  'magdalena': 'Magda',
  'joanna': 'Joasia',
  'monika': 'Moniczka',
  'dorota': 'Dorotka',
  'aleksandra': 'Ola',
  'natalia': 'Natalka',
  'karolina': 'Karolinka',
  'justyna': 'Justynka',
  'beata': 'Beatka',
  'iwona': 'Iwonka',
  'marta': 'Martusia',
  'paulina': 'Paulinka',
  'sylwia': 'Sylwia',
  'renata': 'Renatka',
  'weronika': 'Weroniczka',
  'patrycja': 'Patrycja',
  'julia': 'Julka',
  'dominika': 'Dominika',
  'gabriela': 'Gabrysia',
  'adrianna': 'Adrianna',
  'klaudia': 'Klaudia',
  'kamila': 'Kamilka',
  'sandra': 'Sandra',
  'nicole': 'Niki',
  'nikola': 'Nikola',
  'oliwia': 'Oliwka',
  'amelia': 'Amelka',
  'zuzanna': 'Zuzia',
  'lena': 'Lenka',
  'maja': 'Majka',
  'hanna': 'Hania',
  'alicja': 'Ala',
  'laura': 'Laurka',
  'pola': 'Pola',
  'kornelia': 'Kornelka',
  'emilia': 'Emilka',
  'antonina': 'Tosia',
  'helena': 'Helenka',
  'iga': 'Iga',
  'blanka': 'Blanka',
  'nadia': 'Nadia',
  'kinga': 'Kinga',
  'martyna': 'Martynka',
  'sara': 'Sarka',
  'milena': 'Milenka',
  'wiktoria': 'Wiktoria',
  'olga': 'Olga',
  'izabela': 'Iza',
  'danuta': 'Danka',
  'jadwiga': 'Jadzia',
  'halina': 'Halinka',
  'grażyna': 'Grażynka',
  'grazyna': 'Grażynka',
  'irena': 'Irenka',
  'bożena': 'Bożenka',
  'bozena': 'Bożenka',
  'urszula': 'Ula',
  'jolanta': 'Jola',
  'lucyna': 'Lucynka',
  'lidia': 'Lidka',
  'wanda': 'Wandzia',
  'genowefa': 'Gienia',
  'stefania': 'Stefcia',
  'janina': 'Janka',
  'marianna': 'Marianka',
  'cecylia': 'Cecylka',
  'felicja': 'Felcia',
  'wioletta': 'Wiolka',
  'aneta': 'Anetka',
  'edyta': 'Edytka',
  'angelika': 'Angelika',
  'marlena': 'Marlenka',
};

/**
 * Convert a full name to just the first name in diminutive form
 * @param fullName - Full name (e.g., "Przemysław Kowalski")
 * @returns Diminutive first name (e.g., "Przemek")
 */
export function getDiminutiveName(fullName: string | null | undefined): string {
  if (!fullName) return '';
  
  // Get first name only
  const firstName = fullName.trim().split(' ')[0].toLowerCase();
  
  // Look up diminutive, or capitalize the original first name
  const diminutive = diminutives[firstName];
  
  if (diminutive) {
    return diminutive;
  }
  
  // If no diminutive found, return capitalized first name
  const originalFirstName = fullName.trim().split(' ')[0];
  return originalFirstName.charAt(0).toUpperCase() + originalFirstName.slice(1);
}
